import { Router, type IRouter } from "express";
import healthRouter from "./health";
import generateRouter from "./generate";
import generateWebsiteRouter from "./generate-website";
import generateWebsiteV2Router from "./generate-website-v2";
import generateChatbotRouter from "./generate-chatbot";
import generateAutomationRouter from "./generate-automation";
import generateOrchestratorRouter from "./generate-orchestrator";
import authRouter from "./auth";
import projectsRouter from "./projects";
import subscriptionsRouter from "./subscriptions";
import templatesRouter from "./templates";
import deploymentsRouter from "./deployments";
import memoryRouter from "./memory";
import developerRouter from "./developer";
import v1Router from "./v1";
import webhooksRouter from "./webhooks";
import agentsRouter from "./agents";
import agentTasksRouter from "./agent-tasks";
import agentObjectivesRouter from "./agent-objectives";
import agentMemoryRouter from "./agent-memory";
import executionEngineRouter from "./execution-engine";
import intelligenceRouter from "./intelligence";
import enterpriseRouter from "./enterprise";
import notificationsRouter from "./notifications";
import shareRouter from "./share";
import copilotRouter from "./copilot";
import enhanceRouter from "./enhance";
import executeRouter from "./execute";
import osRouter from "./os";
import impactRouter from "./impact";
import revenueRouter from "./revenue";
import autonomousRouter from "./autonomous";
import integrationsRouter from "./integrations";
import adminRouter from "./admin";
import waitlistRouter from "./waitlist";
import workspaceControllerRouter from "./workspace-controller";
import aiBuilderRouter from "./ai-builder";
import businessGraphRouter from "./business-graph";
import adminBillingRouter from "./admin-billing";
import sessionMonitorRouter from "./session-monitor";
import supportRouter from "./support";
import adminImpersonationRouter from "./admin-impersonation";
import adminCrmRouter from "./admin-crm";
import adminAcquisitionRouter from "./admin-acquisition";
import adminFeatureFlagsRouter from "./admin-feature-flags";
import adminHealthRouter from "./admin-health";
import adminAiModelsRouter from "./admin-ai-models";
import adminSecurityRouter from "./admin-security";
import adminIncidentsRouter from "./admin-incidents";
import adminBackupsRouter from "./admin-backups";
import onboardingRouter from "./onboarding";
import referralsRouter from "./referrals";
import adminErrorsRouter from "./admin-errors";
import adminRetentionRouter from "./admin-retention";
import workerRouter from "./worker";
import websiteV2ProjectsRouter from "./website-v2-projects";
import editWebsiteV2Router from "./edit-website-v2";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(generateRouter);
router.use(generateWebsiteRouter);
router.use(generateWebsiteV2Router);
router.use(generateChatbotRouter);
router.use(generateAutomationRouter);
router.use(generateOrchestratorRouter);
router.use(subscriptionsRouter);
router.use(templatesRouter);
router.use(deploymentsRouter);
router.use(memoryRouter);
router.use(developerRouter);
router.use(v1Router);
router.use(webhooksRouter);
router.use(agentsRouter);
router.use(agentTasksRouter);
router.use(agentObjectivesRouter);
router.use(agentMemoryRouter);
router.use(executionEngineRouter);
router.use(intelligenceRouter);
router.use(enterpriseRouter);
router.use(notificationsRouter);
router.use(shareRouter);
router.use(copilotRouter);
router.use(enhanceRouter);
router.use(executeRouter);
router.use(osRouter);
router.use(impactRouter);
router.use(revenueRouter);
router.use(autonomousRouter);
router.use(integrationsRouter);
router.use(adminRouter);
router.use(waitlistRouter);
router.use(workspaceControllerRouter);
router.use(aiBuilderRouter);
router.use(businessGraphRouter);
router.use(adminBillingRouter);
router.use(sessionMonitorRouter);
router.use(supportRouter);
router.use(adminImpersonationRouter);
router.use(adminCrmRouter);
router.use(adminAcquisitionRouter);
router.use(adminFeatureFlagsRouter);
router.use(adminHealthRouter);
router.use(adminAiModelsRouter);
router.use(adminSecurityRouter);
router.use(adminIncidentsRouter);
router.use(adminBackupsRouter);
router.use(onboardingRouter);
router.use(referralsRouter);
router.use(adminErrorsRouter);
router.use(adminRetentionRouter);
router.use(workerRouter);
router.use(websiteV2ProjectsRouter);
router.use(editWebsiteV2Router);

export default router;
