import { Router, type IRouter } from "express";
import healthRouter from "./health";
import generateRouter from "./generate";
import generateWebsiteRouter from "./generate-website";
import generateChatbotRouter from "./generate-chatbot";
import generateAutomationRouter from "./generate-automation";
import generateOrchestratorRouter from "./generate-orchestrator";
import authRouter from "./auth";
import projectsRouter from "./projects";
import subscriptionsRouter from "./subscriptions";
import templatesRouter from "./templates";
import deploymentsRouter from "./deployments";
import memoryRouter from "./memory";
import developerRouter from "./developer";
import v1Router from "./v1";
import webhooksRouter from "./webhooks";
import agentsRouter from "./agents";
import agentTasksRouter from "./agent-tasks";
import agentObjectivesRouter from "./agent-objectives";
import agentMemoryRouter from "./agent-memory";
import executionEngineRouter from "./execution-engine";
import intelligenceRouter from "./intelligence";
import enterpriseRouter from "./enterprise";
import notificationsRouter from "./notifications";
import shareRouter from "./share";
import copilotRouter from "./copilot";
import enhanceRouter from "./enhance";
import executeRouter from "./execute";
import osRouter from "./os";
import impactRouter from "./impact";
import revenueRouter from "./revenue";
import autonomousRouter from "./autonomous";
import integrationsRouter from "./integrations";
import adminRouter from "./admin";
import waitlistRouter from "./waitlist";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(generateRouter);
router.use(generateWebsiteRouter);
router.use(generateChatbotRouter);
router.use(generateAutomationRouter);
router.use(generateOrchestratorRouter);
router.use(subscriptionsRouter);
router.use(templatesRouter);
router.use(deploymentsRouter);
router.use(memoryRouter);
router.use(developerRouter);
router.use(v1Router);
router.use(webhooksRouter);
router.use(agentsRouter);
router.use(agentTasksRouter);
router.use(agentObjectivesRouter);
router.use(agentMemoryRouter);
router.use(executionEngineRouter);
router.use(intelligenceRouter);
router.use(enterpriseRouter);
router.use(notificationsRouter);
router.use(shareRouter);
router.use(copilotRouter);
router.use(enhanceRouter);
router.use(executeRouter);
router.use(osRouter);
router.use(impactRouter);
router.use(revenueRouter);
router.use(autonomousRouter);
router.use(integrationsRouter);
router.use(adminRouter);
router.use(waitlistRouter);

export default router;
