export enum RuntimeEvent {
  BOOT_STARTED = "BOOT_STARTED",
  BOOT_COMPLETED = "BOOT_COMPLETED",

  MOUNT_STARTED = "MOUNT_STARTED",
  MOUNT_COMPLETED = "MOUNT_COMPLETED",

  INSTALL_STARTED = "INSTALL_STARTED",
  INSTALL_COMPLETED = "INSTALL_COMPLETED",

  SERVER_STARTED = "SERVER_STARTED",
  SERVER_READY = "SERVER_READY",

  FILE_CHANGED = "FILE_CHANGED",

  TERMINAL_OUTPUT = "TERMINAL_OUTPUT",

  ERROR = "ERROR",
}