/**
 * STAGEONE Execution Bus — Shared Types
 */

/**
 * Every execution passes through these phases in order.
 *
 * IDLE                  — No execution in progress.
 * ROUTING               — Command received, resolving module and controller.
 * WAITING_FOR_CONTROLLER — Controller not yet registered (page not mounted).
 *                          Bus has navigated and is waiting for registerController()
 *                          to fire, which will auto-resume the execution.
 * POPULATING            — controller.navigate() + controller.populate() running.
 * CONFIRMATION_WAIT     — Population complete; waiting for approve() call.
 *                         Auto-approves immediately when payload.autoGenerate = true.
 * GENERATING            — controller.generate() running (SSE pipeline active).
 * STREAMING             — SSE chunks actively arriving (sub-phase of GENERATING;
 *                         tracked by module-level lifecycle events, not the bus).
 * SAVING                — Project persistence running (sub-phase; ditto).
 * COMPLETED             — All phases resolved successfully.
 * ERROR                 — A phase failed; execution is terminal.
 */
export type ExecutionPhase =
  | 'IDLE'
  | 'ROUTING'
  | 'WAITING_FOR_CONTROLLER'
  | 'POPULATING'
  | 'CONFIRMATION_WAIT'
  | 'GENERATING'
  | 'STREAMING'
  | 'SAVING'
  | 'COMPLETED'
  | 'ERROR';

/** Module identifiers — must stay in sync with module-architecture ModuleId. */
export type ExecutionModuleId =
  | 'intelligence'
  | 'website'
  | 'chatbot'
  | 'automation'
  | 'orchestrator';

/**
 * Action variants:
 *   populate — hydrate inputs only; stop at CONFIRMATION_WAIT.
 *   generate — generate immediately (assumes inputs are already populated).
 *   run      — full flow: populate → (confirm) → generate.
 */
export type ExecutionAction = 'populate' | 'generate' | 'run';

/** Data carried into an execution command. */
export interface ExecutionPayload {
  /** The business idea or prompt to populate into the module. */
  idea?: string;
  /** Optional project linkage. */
  projectId?: string;
  /** Optional user context. */
  userId?: string;
  /**
   * When true the bus skips CONFIRMATION_WAIT and proceeds directly to GENERATING.
   * Use for programmatic/Copilot-driven full-run flows.
   * When false (default) the bus parks at CONFIRMATION_WAIT until approve() is called.
   */
  autoGenerate?: boolean;
  /** Arbitrary extra data forwarded to the module controller. */
  metadata?: Record<string, unknown>;
  /**
   * Execution trace ID (from the execution-tracer). Set by the caller (Marcus /
   * copilot-panel) at Stage 1 so the bus and downstream module pages can log
   * against the same trace via tracer.getActiveExecutionId(module).
   * Tracing-only field — does not affect dispatch behaviour.
   */
  _traceId?: string;
}

/** Execution command — the input to ExecutionBus.execute(). */
export interface ExecutionCommand {
  module: ExecutionModuleId;
  action: ExecutionAction;
  payload?: ExecutionPayload;
}

/**
 * A live record of one execution run.
 * Created on execute(), updated on every phase transition.
 */
export interface ExecutionRecord {
  /** Unique ID for this execution run (generated by the bus). */
  executionId: string;
  moduleId: ExecutionModuleId;
  phase: ExecutionPhase;
  status: 'active' | 'completed' | 'failed' | 'cancelled';
  payload?: ExecutionPayload;
  /** Unix ms — when execute() was called. */
  startedAt: number;
  /** Unix ms — last phase transition. */
  updatedAt: number;
  /** Unix ms — set when status reaches completed/failed/cancelled. */
  completedAt?: number;
  /** Set when status = 'failed'. */
  error?: string;
}
